[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"




[project]
name = "rubric"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
score = "rubric.score:main"


# Hatchling configuration (replaces setuptools.packages.find)
[tool.hatch.build.targets.wheel]
packages = ["rubric"]
